// Code generated by hertz generator.

package main

import (
	"hertz-starter-kit/biz/dal"
	"hertz-starter-kit/biz/middleware"
	"hertz-starter-kit/pkg/config"
	"hertz-starter-kit/pkg/logger"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// 读取配置
	config.SetupConfig()
	// 日志相关
	logger.SetupLogger()
	// 连接数据库、自动迁移 schema
	dal.SetupConn()

	h := server.Default(
		server.WithHostPorts(":8080"),
		server.WithBasePath("/api/"),
		server.WithHandleMethodNotAllowed(true),
	)
	h.Use(middleware.GlobalErrorHandler)
	register(h)
	h.Spin()
}
