// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/pkg/errors"
	user "hertz-starter-kit/biz/model/user"
	"hertz-starter-kit/pkg/errcode"
	"hertz-starter-kit/pkg/utils"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		// 业务代码中将错误存放到app.RequestContext中直接退出
		//c.String(consts.StatusBadRequest, err.Error())
		_ = c.Error(errors.WithStack(errcode.NewInvalidError(err)))
		return
	}

	hlog.CtxInfof(ctx, "")

	resp := new(user.RegisterResponse)

	utils.NewResponse(c).ToResponse(resp)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(errors.WithStack(errcode.NewInvalidError(err)))
		return
	}

	resp := new(user.LoginResponse)

	utils.NewResponse(c).ToResponse(resp)
}

// Info .
// @router /user/:username [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.InfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(errors.WithStack(errcode.NewInvalidError(err)))
		return
	}

	resp := new(user.InfoResponse)

	utils.NewResponse(c).ToResponse(resp)
}
