server:
  run_mode: debug
  http_port: 8000
  read_timeout: 60
  write_timeout: 60
app:
  default_pageSize: 10
  max_page_size: 100
  log_save_path: storage/logs
  log_file_name: hertz_app
  log_file_ext: .log
database:
  type: mysql
  username: root  # 填写你的数据库账号
  password: rootroot  # 填写你的数据库密码
  host: 127.0.0.1:3306
  name: hertz_app_service
  table_prefix: hertz_
  charset: utf8mb4
  parse_time: True
  max_idle_conns: 10
  max_open_conns: 30